"""Small deployment boundary; task intelligence lives in workspace programs."""
from __future__ import annotations

from typing import Any, Mapping, Protocol


class RobotDeployment(Protocol):
    @property
    def instruction(self) -> str: ...
    def dispatch(self, method: str, arguments: Mapping[str, Any]) -> Any: ...
    def initial_observation(self) -> Mapping[str, Any]: ...
    def project_rpc_output(self, method: str, arguments: Mapping[str,Any],
                           result: Any) -> Any: ...
    def canonical_embodied_state(self) -> Mapping[str, Any]: ...
    def canonical_observation(self, observation: Mapping[str, Any]) -> Mapping[str, Any]: ...
    def project_public_entities(self, tool_id: str, result: Any) -> list[Mapping[str, Any]]: ...
    def register_capability(self, tool_id: str, function: Any,
                            contract: Mapping[str, Any]) -> None: ...
    def sensor_report(self, execution: Mapping[str, Any]) -> Mapping[str, Any]: ...
    def agent_evidence(self, execution: Mapping[str, Any],
                       sensor_report: Mapping[str, Any]) -> Mapping[str, Any]: ...
    def verification_receipt(self, execution: Mapping[str, Any]) -> Mapping[str, Any]: ...
    def execution_identity(self) -> Mapping[str, Any]: ...
    def resume_protocol(self) -> Mapping[str, Any]: ...
    def validate_execution_receipt(self, receipt: Mapping[str, Any]) -> bool: ...
    def reset_case(self) -> Mapping[str, Any]: ...
    def close(self) -> None: ...


# One transport verb exposes the Controller's ordinary Python Robot SDK.
# Individual embodied primitives remain SDK methods, not OpenHands tools.
ALLOWED_RPC = frozenset({"observe", "act", "use", "verify", "record", "sdk"})

__all__ = ["ALLOWED_RPC", "RobotDeployment"]
