assets: /data/zxy/LIBERO-PRO/libero/libero/assets
bddl_files: /data/zxy/LIBERO-PRO/libero/libero/bddl_files
benchmark_root: /data/zxy/LIBERO-PRO/libero/libero
datasets: /data/zxy/LIBERO-PRO/libero/datasets
init_states: /data/zxy/LIBERO-PRO/libero/libero/init_files
